---
theme: jekyll-theme-minimal

title: Chien-Jens Chen

logo: "/img/myself.jpg"

author: Chien-Jens Chen
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: DarkRed;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}

</style>
