theme: jekyll-theme-minimal

title: Chien-Jens Chen

logo: "/img/myself.jpg"

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "https://chienjens.github.io/"
  

