# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            ChenChien
tagline:          ' ||  Chien-Jens Home'
description:      'My name is Chien-Jens Chen, here is my <a href="https://www.facebook.com/chien.chen.98">Facebook</a>.'
url:              https://chienjens.github.io/
baseurl:          /

author:
  name:           'Chien-Jens Chen'
  url:            https://www.facebook.com/chien.chen.98

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://chienjens.github.io/
