# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : ChenChien
tagline             : ' ||  Chien-Jens Home'
description         : 'Welcome to Chien-Jens web!'
url                 : https://chienjens.github.io/
baseurl             : https://chienjens.github.io/

author              : Chien-Jens Chen
name                : 'Chien-Jens Chen'
url                 : https://chienjens.github.io/

paginate            : 5

# Custom vars
picture             : "/img/homemyself3.png"

github_username     : chienjens
facebook_username   : chien.chen.98
linkedin_username   : 建仁-陳-296b87122/
gmail_username      : chienjens@gmail.com
repo                : https://chienjens.github.io/
